### ISSUE TITLE
Payload for NS

### ISSUE THREAD

**Issue by Skalke** [GaryOderNichts/udpih#3]
How hard is it to change the code to create an uf2 payload for forwarding to a switch?

**Comment by GaryOderNichts** [comment]
What do you mean exactly?
Using udpih to hack a switch? That's not possible since the switch doesn't have this vulnerability, and even if it did it wouldn't be possible to exploit it to gain code execution.
Or using udpih to hack a Wii U with a Switch? For that [udpih_nxpayload](https://github.com/GaryOderNichts/udpih_nxpayload) already exists.
